controller_list:
  - name: ''
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - robot_joint_s
      - robot_joint_l
      - robot_joint_u
      - robot_joint_r
      - robot_joint_b
      - robot_joint_t
